import "./globals.scss";
import { raleway, manrope } from "./fonts";
import { ProgressBar, ProgressBarProvider } from "react-transition-progress";
import styles from "./page.module.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} ${manrope.variable} font-sans`}>
        <ProgressBarProvider>
          <ProgressBar className={styles.progressbar} />
          {children}
        </ProgressBarProvider>
      </body>
    </html>
  );
}
