import './globals.scss'
import { raleway } from './fonts'
import styles from './page.module.scss'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
          {children}
      </body>
    </html>
  )
}
